# Generated by Django 4.1.3 on 2022-11-03 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classID', models.CharField(max_length=3, unique=True)),
                ('classname', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectID', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('subjectname', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termname', models.CharField(max_length=10)),
                ('academicyear', models.CharField(max_length=4)),
            ],
            options={
                'unique_together': {('termname', 'academicyear')},
            },
        ),
        migrations.CreateModel(
            name='TeacherRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_employed', models.CharField(max_length=4)),
                ('national_id', models.CharField(max_length=8, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=10)),
                ('auth_id', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('regNo', models.CharField(max_length=20, unique=True)),
                ('yearofAdmission', models.CharField(max_length=4)),
                ('date', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('auth_id', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='classteacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='base.teacherregistration'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examtype', models.CharField(max_length=10)),
                ('marks', models.IntegerField(default=0)),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.studentregistration')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.term')),
            ],
            options={
                'unique_together': {('examtype', 'studentID', 'subject', 'term')},
            },
        ),
    ]
