# Generated by Django 4.1.3 on 2022-11-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='date',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='studentregistration',
            old_name='yearofAdmission',
            new_name='year_of_admission',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='regNo',
        ),
    ]
