# Generated by Django 4.0.3 on 2022-11-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_studentregistration_auth_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherregistration',
            name='dateofbirth',
            field=models.DateField(),
        ),
    ]
